### PR TITLE
#8 :Feature/task update

### PR DESCRIPTION
**Pull request by piyushkumar079**
## Task Update Functionality Implementation
#8 
### Problem
The application currently lacks the ability for users to update tasks after creation, which limits their flexibility in managing task details.
### Solution Overview
To address this issue, I implemented the following changes:
- Created an `EditForm.js` component to provide a user interface element for editing task details.
- Implemented conditional rendering to display the edit form when the user chooses to update a task.
- Integrated frontend logic to interact with the backend API by dispatching the `CHANGE_TASK` action to update task data.
- used the PATCH route availed by the backend which updates the code in backend 
### Screenshots/Video
Attached screenshots/video showcasing the updated user interface with the task update functionality.
https://github.com/iiitl/MERN_AUTH/assets/143178077/35c43660-7fa1-4980-9ee2-eb84f095cdcb
### Additional Notes
Since my main branch is ahead of the MERN_AUTH repo. I wasn't able to figure out how to start with a fresh copy of the repo
but next time I will keep in mind of creating a new branch which is in sync with the main branch of the repo
PS- This #8 was actually difficult to implement , although enjoyed working on it
Please review and provide feedback. Thank you!

### CODE REVIEW

**Comment by Yash7426** [comment]
@piyushkumar079  , when addressing each issue, create a new branch from main. Ensure that your pull request only contains commits relevant to the specific issue being solved, excluding any commits from previous issues.

**Comment by piyushkumar079** [comment]
> @piyushkumar079 , when addressing each issue, create a new branch from main. Ensure that your pull request only contains commits relevant to the specific issue being solved, excluding any commits from previous issues.

I wasn't credited any points for this pr
should I make a new branch and then create a new PR?

**Comment by Yash7426** [comment]
> > @piyushkumar079 , when addressing each issue, create a new branch from main. Ensure that your pull request only contains commits relevant to the specific issue being solved, excluding any commits from previous issues.
> 
> I wasn't credited any points for this pr
> should I make a new branch and then create a new PR?
> 

Yes, for this PR and previous PR's too.

**Comment by piyushkumar079** [comment]
> > > @piyushkumar079 , when addressing each issue, create a new branch from main. Ensure that your pull request only contains commits relevant to the specific issue being solved, excluding any commits from previous issues.
> > 
> > 
> > I wasn't credited any points for this pr
> > should I make a new branch and then create a new PR?
> 
> Yes, for this PR and previous PR's too.

just made new PR for the previous issues with new branch for each new issue.
Thank you for the guidance!

**Pull request closed without merging**
